parent=keycloak.v2
import=common/keycloak
styles=css/login.css css/ai-agent-os-v3.css
stylesCommon=web_components/webcomponents-lite.js
locales=en,ar
internationalizationEnabled=true

meta=viewport==width=device-width,initial-scale=1,user-scalable=no
