/**
 * Atomic Red Team (https://github.com/redcanaryco/atomic-red-team) publishes
 * one YAML definition per MITRE ATT&CK technique, under
 * `atomics/<Txxxx>/<Txxxx>.yaml`. The project itself is _offensive_ tooling
 * that ships commands an operator can run to emulate an attack. The reader
 * in this module does **not** execute anything — it parses the YAML so a
 * defender (SIEM / detection engineer) can see which indicators to look for.
 *
 * All functions are pure and operate on strings or pre-read files. The
 * higher-level scan function walks a local clone and is the only I/O entry
 * point. Nothing here ever touches the network or runs a subprocess.
 */

import { parse as parseYaml } from 'yaml';
import { readFile, readdir, stat } from 'node:fs/promises';
import { join, resolve } from 'node:path';

export type AtomicPlatform = 'windows' | 'linux' | 'macos' | 'containers' | 'iaas' | 'office-365' | 'azure-ad' | string;

export interface AtomicExecutor {
  readonly name: string;
  readonly command?: string;
  readonly elevationRequired?: boolean;
  readonly cleanupCommand?: string;
}

export interface AtomicTest {
  readonly name: string;
  readonly description?: string;
  readonly platforms: AtomicPlatform[];
  readonly executor?: AtomicExecutor;
  readonly inputArguments?: Record<string, { description?: string; type?: string; default?: unknown }>;
  readonly dependencies: string[];
  readonly autoGeneratedGuid?: string;
}

export interface AtomicTechnique {
  readonly id: string;
  readonly displayName: string;
  readonly tests: AtomicTest[];
  readonly sourceFile: string;
  readonly errors: string[];
}

export interface AtomicSummary {
  readonly techniques: AtomicTechnique[];
  readonly total: number;
  readonly byPlatform: Record<string, number>;
  readonly errors: string[];
}

export interface AtomicScanOptions {
  /** Absolute path to a local `atomic-red-team` clone. */
  readonly rootPath: string;
  /** Optional filter: only techniques matching any of these MITRE ids. */
  readonly techniqueIds?: string[];
  /** Optional filter: only tests supporting any of these platforms. */
  readonly platforms?: AtomicPlatform[];
  /** Case-insensitive substring filter over technique display name + test name. */
  readonly query?: string;
  /** Cap the number of techniques returned (default 200). */
  readonly limit?: number;
  /** Override `fs.readFile` for tests. */
  readonly readFileImpl?: (path: string) => Promise<string>;
  /** Override the directory walker for tests. */
  readonly walkImpl?: (rootPath: string) => Promise<string[]>;
}

/**
 * Parse a single Atomic Red Team YAML string into an AtomicTechnique. Pure:
 * never throws, collects parse issues into `errors`.
 */
export function parseAtomicTechniqueYaml(source: string, sourceFile = '<inline>'): AtomicTechnique {
  const errors: string[] = [];
  let doc: unknown;
  try {
    doc = parseYaml(source);
  } catch (err) {
    return {
      id: '',
      displayName: '',
      tests: [],
      sourceFile,
      errors: [`yaml parse error: ${err instanceof Error ? err.message : String(err)}`],
    };
  }
  if (!doc || typeof doc !== 'object') {
    return { id: '', displayName: '', tests: [], sourceFile, errors: ['root is not an object'] };
  }
  const root = doc as Record<string, unknown>;
  const id = typeof root.attack_technique === 'string' ? root.attack_technique : '';
  const displayName = typeof root.display_name === 'string' ? root.display_name : '';
  if (!id) errors.push('missing attack_technique');

  const rawTests = Array.isArray(root.atomic_tests) ? root.atomic_tests : [];
  const tests: AtomicTest[] = [];
  for (const raw of rawTests) {
    if (!raw || typeof raw !== 'object') continue;
    const t = raw as Record<string, unknown>;
    const platforms = Array.isArray(t.supported_platforms)
      ? (t.supported_platforms.filter((p): p is string => typeof p === 'string') as string[])
      : [];
    const dependencies = Array.isArray(t.dependencies)
      ? (t.dependencies
          .map((d) => (d && typeof d === 'object' && 'description' in d ? (d as { description: unknown }).description : null))
          .filter((x): x is string => typeof x === 'string') as string[])
      : [];
    const executor = extractExecutor(t.executor);
    tests.push({
      name: typeof t.name === 'string' ? t.name : '(unnamed)',
      description: typeof t.description === 'string' ? t.description : undefined,
      platforms,
      executor,
      inputArguments:
        t.input_arguments && typeof t.input_arguments === 'object'
          ? (t.input_arguments as Record<string, { description?: string; type?: string; default?: unknown }>)
          : undefined,
      dependencies,
      autoGeneratedGuid: typeof t.auto_generated_guid === 'string' ? t.auto_generated_guid : undefined,
    });
  }

  return { id, displayName, tests, sourceFile, errors };
}

function extractExecutor(raw: unknown): AtomicExecutor | undefined {
  if (!raw || typeof raw !== 'object') return undefined;
  const e = raw as Record<string, unknown>;
  const name = typeof e.name === 'string' ? e.name : 'unknown';
  return {
    name,
    command: typeof e.command === 'string' ? e.command : undefined,
    elevationRequired: typeof e.elevation_required === 'boolean' ? e.elevation_required : undefined,
    cleanupCommand: typeof e.cleanup_command === 'string' ? e.cleanup_command : undefined,
  };
}

/**
 * Filter a pre-loaded collection of AtomicTechniques in memory.
 * Pure, deterministic — unit testable without touching disk.
 */
export function filterAtomicTechniques(
  techniques: AtomicTechnique[],
  filters: Pick<AtomicScanOptions, 'techniqueIds' | 'platforms' | 'query' | 'limit'>,
): AtomicSummary {
  const errors: string[] = [];
  const normalizedIds = new Set((filters.techniqueIds ?? []).map((s) => s.toUpperCase()));
  const normalizedPlatforms = new Set((filters.platforms ?? []).map((p) => p.toLowerCase()));
  const queryLower = filters.query ? filters.query.toLowerCase() : undefined;
  const limit = filters.limit ?? 200;

  const out: AtomicTechnique[] = [];
  const byPlatform: Record<string, number> = {};

  for (const tech of techniques) {
    for (const e of tech.errors) errors.push(`${tech.sourceFile}: ${e}`);
    if (normalizedIds.size > 0 && !normalizedIds.has(tech.id.toUpperCase())) continue;

    let tests = tech.tests;
    if (normalizedPlatforms.size > 0) {
      tests = tests.filter((t) => t.platforms.some((p) => normalizedPlatforms.has(p.toLowerCase())));
    }
    if (queryLower) {
      const matchesTechnique = tech.displayName.toLowerCase().includes(queryLower);
      tests = matchesTechnique
        ? tests
        : tests.filter((t) =>
            t.name.toLowerCase().includes(queryLower) ||
            (t.description ?? '').toLowerCase().includes(queryLower),
          );
    }
    if (tests.length === 0 && (normalizedPlatforms.size > 0 || queryLower)) continue;

    for (const t of tests) {
      for (const p of t.platforms) byPlatform[p] = (byPlatform[p] ?? 0) + 1;
    }
    out.push({ ...tech, tests });
    if (out.length >= limit) break;
  }

  return {
    techniques: out,
    total: out.reduce((acc, t) => acc + t.tests.length, 0),
    byPlatform,
    errors,
  };
}

/**
 * Walk a local clone of Atomic Red Team, read every technique YAML under
 * `atomics/`, and return a filtered summary. Soft-fails on invalid roots,
 * unreadable files, and YAML parse errors.
 */
export async function scanAtomicRedTeam(opts: AtomicScanOptions): Promise<AtomicSummary> {
  const errors: string[] = [];
  if (!opts.rootPath || typeof opts.rootPath !== 'string') {
    return { techniques: [], total: 0, byPlatform: {}, errors: ['rootPath is required'] };
  }
  const read = opts.readFileImpl ?? ((p: string) => readFile(p, 'utf8'));
  const walk = opts.walkImpl ?? defaultWalk;

  let files: string[];
  try {
    files = await walk(opts.rootPath);
  } catch (err) {
    return {
      techniques: [],
      total: 0,
      byPlatform: {},
      errors: [`scan failed: ${err instanceof Error ? err.message : String(err)}`],
    };
  }
  if (files.length === 0) {
    errors.push(`no technique YAML files found under ${opts.rootPath}`);
  }

  const techniques: AtomicTechnique[] = [];
  for (const file of files) {
    try {
      const source = await read(file);
      techniques.push(parseAtomicTechniqueYaml(source, file));
    } catch (err) {
      techniques.push({
        id: '',
        displayName: '',
        tests: [],
        sourceFile: file,
        errors: [`read failed: ${err instanceof Error ? err.message : String(err)}`],
      });
    }
  }

  const summary = filterAtomicTechniques(techniques, opts);
  return { ...summary, errors: [...errors, ...summary.errors] };
}

async function defaultWalk(rootPath: string): Promise<string[]> {
  const atomics = resolve(rootPath, 'atomics');
  let exists: boolean;
  try {
    const st = await stat(atomics);
    exists = st.isDirectory();
  } catch {
    exists = false;
  }
  const root = exists ? atomics : resolve(rootPath);
  const out: string[] = [];
  for (const entry of await readdir(root, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    if (!/^T\d{4}(?:\.\d{3})?$/i.test(entry.name)) continue;
    const file = join(root, entry.name, `${entry.name}.yaml`);
    try {
      const st = await stat(file);
      if (st.isFile()) out.push(file);
    } catch {
      // Not every directory carries a top-level yaml; skip silently.
    }
  }
  return out.sort();
}
